name: aws_storage_service
description: A package that handles Uploads and Downloads to the AWS S3 service
version: 1.1.1
environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.2
  dio: ^5.0.3
  http: ^1.1.0
  mocktail: ^0.3.0
  path: ^1.8.0
  rxdart: ^0.27.7
  state_notifier: ^0.7.0
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
